rbm2m/models/base.py
# -*- coding: utf-8 -*-
from flask.json import JSONEncoder as BaseJSONEncoder
from sqlalchemy.ext.declarative import declarative_base as real_declarative_base

# Let's make this a class decorator
declarative_base = lambda cls: real_declarative_base(cls=cls)


@declarative_base
class Base(object):

    """
    Add some default properties and methods to the SQLAlchemy declarative base.
    """
    __table_args__ = {
        'mysql_engine': 'InnoDB',
        'mysql_charset': 'utf8',
        'mysql_collate': 'utf8_general_ci'
    }

    @property
    def columns(self):
        return [c.name for c in self.__table__.columns]

    @property
    def column_items(self):
        return dict([(c, getattr(self, c)) for c in self.columns])

    def to_dict(self):
        return {c.name: getattr(self, c.name) for c in self.__table__.columns}

    def __repr__(self):
        return '<{}({})>'.format(self.__class__.__name__, self.column_items)


class JsonSerializer(object):

    """A mixin that can be used to mark a SQLAlchemy model class which
    implements a :func:`to_json` method. The :func:`to_json` method is used
    in conjuction with the custom :class:`JSONEncoder` class. By default this
    mixin will assume all properties of the SQLAlchemy model are to be visible
    in the JSON output. Extend this class to customize which properties are
    public, hidden or modified before being being passed to the JSON serializer.
    """

    __json_public__ = None
    __json_hidden__ = None
    __json_modifiers__ = None

    def get_field_names(self):
        for p in self.__mapper__.iterate_properties:
            yield p.key

    def to_json(self):
        field_names = self.get_field_names()

        public = self.__json_public__ or field_names
        hidden = self.__json_hidden__ or []
        modifiers = self.__json_modifiers__ or dict()

        rv = dict()
        for key in public:
            rv[key] = getattr(self, key)
        for key, modifier in modifiers.items():
            value = getattr(self, key)
            rv[key] = modifier(value, self)
        for key in hidden:
            rv.pop(key, None)
        return rv


class JSONEncoder(BaseJSONEncoder):

    """Custom :class:`JSONEncoder` which respects objects that include the
    :class:`JsonSerializer` mixin.
    """

    def default(self, obj):
        if isinstance(obj, JsonSerializer):
            return obj.to_json()
        return super(JSONEncoder, self).default(obj)

rbm2m/models/record.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import datetime
from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey, Index
from sqlalchemy.orm import relationship, backref

from rbm2m.models.base import JsonSerializer
from .base import Base

FLAGS = {
    # Marks record that must not appear in export
    'sold': {
        'label': 'Продано',
        'description': 'Запись продана и не попадает в экспорт',
        'css_class': '',
        'readonly': False

    },
    # Marks record for which one or more images was not imported
    'missing_images': {
        'label': 'Ошибка при загрузке картинок',
        'description': 'Не удалось загрузить одну или несколько картинок для этой записи',
        'css_class': 'alert',
        'readonly': True
    }
}


class Record(Base, JsonSerializer):
    __tablename__ = 'records'

    id = Column(Integer, primary_key=True, autoincrement=False)
    import_date = Column(DateTime, default=datetime.datetime.utcnow,
                         nullable=False)
    artist = Column(String(250), nullable=False)
    title = Column(String(250), nullable=False)
    label = Column(String(250), nullable=False)
    notes = Column(Text)
    grade = Column(String(16), nullable=False)
    format = Column(String(2), nullable=False)
    price = Column(Integer)

    genre_id = Column(Integer, ForeignKey('genres.id'), nullable=False)
    genre = relationship("Genre", uselist=False, lazy='joined',
                         backref=backref('records', lazy='dynamic'))

    flags = relationship('RecordFlag',  lazy='dynamic',
                         backref=backref('record'))


class RecordFlag(Base):
    __tablename__ = 'record_flags'

    id = Column(Integer, primary_key=True)
    record_id = Column(Integer, ForeignKey(Record.id))
    name = Column(String(50), nullable=False)

Index('ix_record_id_name', RecordFlag.record_id, RecordFlag.name)

rbm2m/views/api.py
# -*- coding: utf-8 -*-
from flask import Blueprint, jsonify, current_app, request

from ..webapp import db, redis, basic_auth
from ..action import (stats, scanner, record_manager, genre_manager, user_settings,
                      scan_manager, export_manager, debug)

bp = Blueprint('api', __name__)


@bp.before_request
def check_auth():
    if not basic_auth.authenticate():
        return basic_auth.challenge()


@bp.route('/stats')
def get_stats():
    overview = stats.get_overview(db.session)
    scans = stats.active_scans(db.session)
    return jsonify({'stats': overview, 'scans': scans})


@bp.route('/run_scan/<int:genre_id>')
@bp.route('/run_scan/', defaults={'genre_id': None})
def run_scan(genre_id):
    sc = scanner.Scanner(current_app.config, db.session, redis._redis_client)
    try:
        sc.enqueue_scan(genre_id)
    except scanner.ScanError as e:      # Scan already queued
        return jsonify({'success': False, 'message': str(e)})
    else:
        return jsonify({'success': True})


@bp.route('/abort_scan/<int:scan_id>')
@bp.route('/abort_scan/', defaults={'scan_id': None})
def abort_scan(scan_id=None):
    scn = scanner.Scanner(current_app.config, db.session, redis)

    if scan_id is None:
        scan_id = int(request.args.get('scan_id'))

    try:
        scn.abort_scan(scan_id)
    except scanner.ScanError as e:  # no such scan or scan not started
        return jsonify({'success': False, 'message': str(e)})
    else:
        return jsonify({'success': True})


@bp.route('/update_genre')
def update_genre():
    genre_id = int(request.args['gid'])
    field = request.args['f']
    value = int(request.args['v'])
    genman = genre_manager.GenreManager(db.session)
    genre = genman.get(genre_id)
    setattr(genre, field, value)
    return jsonify({'success': True})


@bp.route('/record_list')
def record_list():
    filters = {k[2:]: int(v) for k, v in request.args.items() if k.startswith('f_') and v}
    search_term = request.args.get('search', None)
    order = request.args.get('order', 'id')
    offset = request.args.get('offset', 0)

    recman = record_manager.RecordManager(db.session)
    records = recman.list(filters=filters, search=search_term, order=order,
                          offset=offset)
    return jsonify({'records': [rec.to_dict() for rec in records]})


@bp.route('/record/<int:rec_id>/toggle_flag')
def toggle_record_flag(rec_id):
    flagname = request.args.get('flagname')
    recman = record_manager.RecordManager(db.session)
    return jsonify({'success': recman.toggle_flag(rec_id, flagname)})


@bp.route('/save_settings', methods=['POST'])
def save_settings():
    settings = user_settings.UserSettings(db.session)

    for item in request.json:
        settings[item['name']] = item['value']

    return jsonify({'success': True})


@bp.route('/run_scheduled')
def run_scheduled():
    """
        Run regular scheduled task
    """
    sc = scanner.Scanner(current_app.config, db.session, redis._redis_client)
    rv = sc.tick()
    return jsonify(rv)


@bp.route('/tidy')
def tidy():
    """
        Run daily cleanup
    """
    sm = scan_manager.ScanManager(db.session)
    sm.clean_up_old_scans()
    em = export_manager.ExportManager(db.session)
    em.clean_up_old_exports()
    dumps_glob = "{}/*.html".format(current_app.config['LOGS_DIR'])
    debug.clean_old_dumps(dumps_glob)
    return jsonify({'success': True})

rbm2m/views/public.py
# -*- coding: utf-8 -*-
import logging

from flask import (Blueprint, render_template, request, send_from_directory,
                   current_app, Response, stream_with_context)

from ..webapp import db
from ..action import exporter


bp = Blueprint('public', __name__)
logger = logging.getLogger(__name__)


@bp.route('/yml')
def yml():
    """
        YML export endpoint
    """

    exp = exporter.YMLExporter(db.session, filters={'format': 'LP'})
    exp.log_export(client_ip(), request.user_agent)
    ctx = {
        'generation_date': exp.generation_date(),
        'genres': exp.category_list(),
        'offers': exp.offers()
    }
    return Response(stream_with_context(stream_template('yml.xml', **ctx)))


@bp.route('/table')
def table():
    """
        Table export endpoint
    """
    exp = exporter.TableExporter(db.session)
    exp.log_export(client_ip(), request.user_agent)

    ctx = {
        'genres': exp.category_list(),
        'rows': exp.rows()
    }
    return Response(stream_with_context(stream_template('table.html', **ctx)))


@bp.route('/media/<path:path>')
def serve_media(path):
    return send_from_directory(current_app.config['MEDIA_DIR'], path)


def client_ip():
    """
        Returns client ip address
    """
    if 'HTTP_X_REAL_IP' in request.environ:
        return request.environ['HTTP_X_REAL_IP']

    return request.remote_addr


def stream_template(template_name, **context):
    """
        Stream rendered template output
    """
    current_app.update_template_context(context)
    t = current_app.jinja_env.get_template(template_name)
    rv = t.stream(context)
    rv.enable_buffering(5)
    return rv

rbm2m/templates/base.html
<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}recordsbymail.com → molotok.ru{% endblock %}</title>
      <link rel="stylesheet"
            href="{{ url_for('static', filename='css/foundation.min.css') }}">
      <link rel="stylesheet"
            href="{{ url_for('static', filename='css/foundation-icons.css') }}">
      <link rel="stylesheet"
            href="{{ url_for('static', filename='css/main.css') }}">
      <script src="{{ url_for('static', filename='js/vendor/modernizr.js') }}"></script>
      <!--[if lte IE 8]>
      <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
      <![endif]-->
	  {% block header %}{% endblock %}
  </head>
  <body>
    {% include "topnav.html" %}
    {% block content %}{% endblock %}

	<script src="{{ url_for('static', filename='js/vendor/jquery.js') }}"></script>
	<script src="{{ url_for('static', filename='js/foundation.min.js') }}"></script>
    <script>$(document).foundation();</script>
    {% block footer %}{% endblock %}
  </body>
</html>

rbm2m/templates/dashboard.html
{% extends "base.html" %}

{% block content %}
<div class="row vspace">
    <div class="large-12 columns">
        <h3>Состояние</h3>

        <ul class="small-block-grid-6 status text-center">
            <li><div><h4 id="status-records_total">-</h4><span>Записей</span></div></li>
            <li><div><h4 id="status-records_in_stock">-</h4><span>В наличии</span></div></li>
            <li><div><h4 id="status-images_total">-</h4><span>Картинок</span></div></li>
            <li><div><h4 id="status-images_total_length">-</h4><span>Гигабайт</span></div></li>
            <li><div><h4 id="status-lots">-</h4><span>Лотов</span></div></li>
            <li><div><h4 id="status-errors">-</h4><span>Ошибок</span></div></li>


        </ul>
    </div>
</div>
<div class="row vspace">
    <div class="large-12 columns">
        <h3>Сканы</h3>
        <ul class="scans">

            <li class="scan" id="scan-template">
                <h1 class="icon"><i class="fi-download"></i></h1>
                <h4>Rock &amp; Pop</h4>

                <div class="right scanstats text-right">
                    <span><span class="items-current">-</span> из
                        <span class="items-total">-</span></span>,
                    <span class="rps">-</span> записей/сек</span>
                    <br>
                    <span>Прошло <span  class="time-elapsed">-</span>
                        осталось <span  class="time-left">-</span></span>
                    <br>

                    <a class="cancel">Отменить</a>

                </div>

                <div class="progress">
                    <span class="meter" style="width: 0%"></span>
                </div>

            </li>

        </ul>
    </div>
</div>


{% endblock %}

{% block footer %}
<script>
    function format_time(sec_num) {
        var hours   = Math.floor(sec_num / 3600);
        var minutes = Math.floor((sec_num - (hours * 3600)) / 60);
        var seconds = sec_num - (hours * 3600) - (minutes * 60);

        if (hours   < 10) {hours   = "0"+hours;}
        if (minutes < 10) {minutes = "0"+minutes;}
        if (seconds < 10) {seconds = "0"+seconds;}
        var time    = hours + ':' + minutes + ':' + Math.round(seconds);
        return time;
    }

    function format_size(size) {
        if(size == null) {
            size = 0;
        }
        return (size/1000000000).toFixed(2);
    }

    function display_status(data, status) {
        for(var key in data['stats']) {

            if(key == 'images_total_length') {
                data['stats'][key] = format_size(data['stats'][key]);
            }
            $('h4#status-' + key).html(data['stats'][key]);
        }


        scan_ids = Array();

        data['scans'].forEach(function(scan, i, scans) {
            var id = 'scan-' + scan['id'];
            scan_ids.push(id);
            var li = $('ul.scans li#' + id);

            if(!li.length) {
                li = $('li#scan-template').clone(true).attr('id', id).appendTo('ul.scans');
            }

            if(scan['num_records'] > 0) {
                var progress = scan['num_records'] / scan['est_num_records'] * 100;
                var sec_elapsed = (new Date() - new Date(scan['started_at'])) / 1000;
                var records_per_sec = 0;
                if(scan['num_records']) {
                    var records_per_sec = scan['num_records'] / sec_elapsed;
                }
                var rps_s = records_per_sec.toFixed(1);
                var sec_left =  (scan['est_num_records'] - scan['num_records']) / records_per_sec;
            } else {
                var progress = 0;
                var sec_left = 0;
                var sec_elapsed= 0;
                var rps_s = 0;

            }


            $(li).find('h4').html(scan['title']);
            $(li).find('span.items-current').html(scan['num_records']);
            $(li).find('span.items-total').html(scan['est_num_records']);
            $(li).find('span.meter').attr('style', 'width: ' + progress + '%;');
            $(li).find('span.time-elapsed').html(format_time(sec_elapsed));
            $(li).find('span.time-left').html(format_time(sec_left));
            $(li).find('span.rps').html(rps_s);
            $(li).find('a.cancel').data('scan_id', scan['id']);

        });

        $('ul.scans li.scan').each(function(){
            var elem = $(this);
            if(scan_ids.indexOf(elem.attr('id')) == -1 && elem.attr('id') != 'scan-template') {
                elem.remove();
            }
        });
    }

    function update_status() {
        $.getJSON("{{ url_for('api.get_stats') }}",{}, display_status);
    }


    $(function (){
        $('a.cancel').on('click', function() {
            $(this).removeClass('cancel').addClass('canceled');
            $.getJSON('{{ url_for("api.abort_scan") }}',
                    {'scan_id': $(this).data('scan_id')},
                    function(data){
                        if(!data['success']) {
                            alert(data['message']);
                        }
            });

        });

        update_status();
        var refreshId = setInterval(update_status, 2000);

    });
</script>
{% endblock %}

rbm2m/templates/env.html
{% extends "base.html" %}

{% block content %}
<div class="row vspace">
    <div class="large-12 columns">
        {% for group_name, group_data in data.items() %}
        <table role="grid" id="envtable">
                <tr>
                    <th colspan="2">
                        {{ group_name }}
                    </th>
                </tr>
                {% for k, v in group_data.items() %}
                <tr>
                    <th>{{ k }}</th>
                    <td>{{ v }}</td>
                </tr>
                {% endfor %}

        </table>
        {% endfor %}
    </div>
</div>
{% endblock %}

rbm2m/templates/export_list.html
{% extends "base.html" %}

{% block content %}
<div class="row vspace">

    <div class="large-12 columns">
        <h3>Ссылки</h3>
        <form>
            <div class="row">
                <div class="large-6 column">
                    <label for="link_yml">YML</label>
                    <input readonly id="link_yml" type="text" value="{{ url_for('public.yml', _external=True) }}">
                </div>
                <div class="large-6 column">
                    <label for="link_table">Источник данных для автообновляющихся таблиц</label>
                    <input readonly id="link_table" type="text" value="{{ url_for('public.table', _external=True) }}">
                </div>
            </div>
            <div class="row">
                <div class="large-6 column">
                    <label for="link_csv">CSV</label>
                    <ul id="link_csv">
                        {% for path in files.csv|sort %}
                        <li>
                            <a href="{{ url_for('public.serve_media', path=path) }}">{{ path }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="large-6 column">
                    <label for="link_xlsx">XLSX</label>
                    <ul id="link_xlsx">
                        {% for path in files.xlsx %}
                        <li>
                            <a href="{{ url_for('public.serve_media', path=path) }}">{{ path }}</a>
                        </li>
                        {% endfor %}
                    </ul>

                    <label for="link_xls">XLS</label>
                    <ul id="link_xls">
                        {% for path in files.xls %}
                        <li>
                            <a href="{{ url_for('public.serve_media', path=path) }}">{{ path }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>

            </div>
        </form>

        <h3>Настройки</h3>

        <form id="settings_form">
        <div id="alertdiv"></div>

            {% for key in settings %}
            <div class="row">
                <div class="large-6 columns">
                    <label>{{ settings[key].title }}

                        {% if settings[key].data_type == 'string' %}
                        <input name="{{ key }}" type="text"
                               placeholder="" value="{{ settings[key].value }}">
                        {% elif settings[key].data_type == 'text' %}
                        <textarea placeholder="" name="{{ key }}"
                                  rows="{{ settings[key].value.count('\n') }}">{{ settings[key].value }}</textarea>
                        {% endif %}
                    </label>
                </div>
                <div class="large-6 columns">
                    {{ settings[key].description|safe }}
                </div>

            </div>

            {% endfor %}

            <button type="button" id="save">Сохранить</button>

        </form>

    </div>
</div>


<div class="row vspace">
    <div class="large-12 columns">

        <h3>Последние операции</h3>

        <table role="grid" class="wide">
            <thead>
            <tr>
                <th>ID</th>
                <th>Формат</th>
                <th>Дата</th>
                <th>IP</th>
                <th>User agent</th>
            </tr>
            </thead>
            <tbody>
            {% for export in exports: %}
            <tr>
                <td>{{ export.id }}</td>
                <td>{{ export.format }}</td>
                <td>{{ export.started_at }}</td>
                <td>{{ export.ip }}</td>
                <td>{{ export.user_agent }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
</div>

<div class="hide">
    <div id="alert-template" data-alert class="alert-box"><a href="#" class="close">&times;</a></div>
</div>

{% endblock %}

{% block footer %}
<script>
    function show_alert(text, cls) {
        $("#alertdiv").empty();
        $('#alert-template').clone().prepend(text).addClass(cls).appendTo("#alertdiv");

    }
    $(function(){
        $('#save').click(function () {
            var data = $('#settings_form').serializeArray();

            $.ajax({
                type: "POST",
                url: "{{ url_for('api.save_settings') }}",
                async: false,
                data: JSON.stringify(data),
                contentType: "application/json",
                complete: function (data) {
                    if(data['success']) {
                        show_alert('Настройки сохранены', 'success');
                    } else {
                        show_alert(data['message'], 'alert');
                    }
                }
            });
        });
    });
</script>
{% endblock %}

rbm2m/templates/genre_list.html
{% extends "base.html" %}

{% block content %}
<div class="row vspace">
    <div class="large-12 columns">
        <h3>Жанры</h3>

        <table role="grid" class="wide">

            <thead>
            <tr>
                <th>ID</th>
                <th>Название</th>
                <th>Импортировать</th>
                <th>Экспортировать</th>
                <th>Запустить скан</th>
            </tr>
            </thead>
            <tbody>
            {% for genre in genres: %}
            <tr>
                <td>{{ genre.id }}</td>
                <td><h5>{{ genre.title }}</h5></td>
                <td>
                    <div class="switch">
                        <input id="import-{{ genre.id }}"
                               data-genre_id="{{ genre.id }}"
                               data-field="import_enabled"
                               type="checkbox"
                               {{ 'checked' if genre.import_enabled else '' }}>
                        <label for="import-{{ genre.id}}"></label>
                    </div>
                </td>
                <td>
                    <div class="switch">

                        <input id="export-{{ genre.id}}"
                               data-genre_id="{{ genre.id }}"
                               data-field="export_enabled"
                               type="checkbox"
                               {{ 'checked' if genre.export_enabled else '' }}>
                        <label for="export-{{ genre.id}}"></label>
                    </div>
                </td>
                <td>
                    <button class="run_scan" data-genre_id="{{ genre.id}}">
                        Запустить
                    </button>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
</div>

{% endblock %}

{% block footer %}
<script>
    $(function(){
        $('.switch input:checkbox').change(function(){
            var gid = $(this).data('genre_id');
            var field = $(this).data('field');
            $.getJSON(
                '{{ url_for("api.update_genre") }}',
                {gid: gid, f: field, v: + this.checked},
                function(data) {
                    if(!data['success']) {
                        alert('Failed to change flag: ' + data['message']);
                    }
                });
        });

        $('button.run_scan').click(function() {
            var elem = $(this);
            $.getJSON(
                '{{ url_for("api.run_scan") }}' + $(this).data('genre_id'), {},
                function(data) {
                    if(data['success']) {
                        elem.html('Запущен').attr('disabled', true);
                    }
                    else {
                        alert('Failed to start scan: ' + data['message']);
                    }
                });
        });
    });
</script>
{% endblock %}

rbm2m/templates/record_list.html
{% extends "base.html" %}

{% block content %}
<div class="row vspace">
    <div class="large-12 columns">
        <h3>Записи</h3>

        <form id="record_filter_form">
            <div class="row">

                <div class="large-4 columns">
                    <select id="f_genre" name="f_genre_id">
                        <option value="">(Все)</option>
                        {% for genre in genres %}
                        <option value="{{ genre.id }}">{{ genre.title }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="large-4 columns">
                    <input type="text" name="search" placeholder="Поиск">
                </div>

            </div>

        </form>

        <table role="grid" class="wide" id="record_table">

            <thead>
            <tr>
                <th>ID</th>
                <th>Исполнитель</th>
                <th>Название</th>
                <th>Метка</th>
                <th>Грейд</th>
                <th>Формат</th>
                <th>Цена</th>
            </tr>
            </thead>
            <tbody></tbody>

            <tfoot class="hide">
            <tr id="rec_template">
                <td class="rec_link"><a href="#">ID</a></td>
                <td class="rec_artist">Исполнитель</td>
                <td class="rec_title">Название</td>
                <td class="rec_label">Метка</td>
                <td class="rec_grade">Грейд</td>
                <td class="rec_format">Формат</td>
                <td class="rec_price">Цена</td>
            </tr>
            </tfoot>
        </table>
    </div>
</div>

{% endblock %}

{% block footer %}
<script>
    function show_records() {
        var qs = $("form#record_filter_form").serialize();
        $.getJSON('{{ url_for("api.record_list") }}' + '?' + qs, {},
            function (data) {

                $('#record_table tbody').empty();

                data['records'].forEach(function(rec, idx, records){
                    var row = $('#rec_template').clone().attr('id', null);
                    for (var key in rec) {
                        row.find('td.rec_' + key).html(rec[key]);
                    }
                    row.find('td.rec_link a')
                        .attr('href', '{{ url_for(".record_view") }}' + rec['id'])
                        .html(rec['id']);

                    $('#record_table tbody').append(row);
                });

            });
    }

    $(function () {
        $('#record_filter_form').submit(function(){ return false;});
        show_records();
        $('form input:checkbox, form select').change(show_records);
        $('form input').keyup(show_records);
    });
</script>
{% endblock %}

rbm2m/templates/record_view.html
{% extends "base.html" %}

{% block content %}

<div class="row vspace">
    <div class="large-12 columns">
        <h3>Просмотр записи</h3>

        <table role="grid" class="wide">
            <tr>
                <th>ID</th>
                <td>{{ record.id }}</td>
            </tr>

            <tr>
                <th>Исполнитель</th>
                <td>{{ record.artist }}</td>
            </tr>

            <tr>
                <th>Название</th>
                <td>{{ record.title }}</td>
            </tr>
            <tr>
                <th>Метка</th>
                <td>{{ record.label }}</td>
            </tr>

            <tr>
                <th>Примечания</th>
                <td>{{ record.notes }}</td>
            </tr>

            <tr>
                <th>Дата импорта</th>
                <td>{{ record.import_date }}</td>
            </tr>

            <tr>
                <th>Грейд</th>
                <td>{{ record.grade }}</td>
            </tr>

            <tr>
                <th>Формат</th>
                <td>{{ record.format }}</td>
            </tr>

            <tr>
                <th>Жанр</th>
                <td>{{ record.genre.title }}</td>
            </tr>

            <tr>
                <th>Цена</th>
                <td>${{ record.price }}</td>
            </tr>

            <tr>
                <th>Флаги</th>
                <td id="flaglist">

                    {% for flag_name, flag in FLAGS.items() %}
                        <span class="label {{ flag.css_class }}">
                            <input type="checkbox" id="fl_{{ flag_name }}"
                                   data-flag_name="{{ flag_name }}"
                                   {% if flag_name in flag_names %}
                                   checked
                                   {% endif %}
                                   {% if flag.readonly %}
                                   disabled
                                   {% endif %}>

                            <label title="{{ flag.description }}"
                                   class="inline"
                                   for="fl_{{ flag_name }}">
                                {{ flag.label }}</label>
                        </span>
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <th>Картинки</th>
                <td>
                    {% for img in record.images %}
                    <div class="record_image_div">
                        <a href="{{ url_for('public.serve_media', path=img.make_filename()) }}">
                            <img class="record_image"
                                 src="{{ url_for('public.serve_media', path=img.make_filename()) }}">
                        </a>
                        
                        ({{ img.length|filesizeformat if img.length else 'Ошибка загрузки'}})
                        <br>
                        <a href="{{ img.url }}">Оригинал</a>
                    </div>
                    {% endfor %}
                </td>

            </tr>

        </table>
    </div>
</div>

{% endblock %}

{% block footer %}
<script>
    $(function () {
        $('#flaglist input:checkbox').change(function () {
            $.getJSON('{{ url_for("api.toggle_record_flag", rec_id=record.id) }}',
                    {'flagname': $(this).data('flag_name')},

                    function (data) {
                        if(!data['success']){
                            alert('Failed to toggle flag');
                        }

                    });
        });
    }) ;
</script>
{% endblock %}

rbm2m/templates/table.html
<table border="1">
    <tr>
        <th>id</th>
        <th>genre</th>
        <th>artist</th>
        <th>title</th>
        <th>label</th>
        <th>grade</th>
        <th>format</th>
        <th>price</th>
        <th>notes</th>
    </tr>
    {% for row in rows %}
    <tr>
        <td>{{ row['id'] }}</td>
        <td>{{ row['genre_title'] }}</td>
        <td>{{ row['artist'] }}</td>
        <td>{{ row['title'] }}</td>
        <td>{{ row['label'] }}</td>
        <td>{{ row['grade'] }}</td>
        <td>{{ row['format'] }}</td>
        <td>{{ row['price'] }}</td>
        <td>{{ row['notes'] }}</td>
    </tr>
    {% endfor %}
</table>